from __future__ import annotations

import csv
from datetime import date, datetime
from io import BytesIO, StringIO
from typing import Any

from flask import Response, send_file
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

from app.services.export_service import ExportService


class DailyBalanceExportService(ExportService):
    """CSV, PDF, and Excel exports for daily sales balance reports."""

    PDF_TEMPLATE = "admin/daily_balance_report_pdf.html"

    @staticmethod
    def _period_label(reports: list[dict[str, Any]]) -> str:
        if not reports:
            return ""
        return f"{reports[-1]['report_date']} to {reports[0]['report_date']}"

    @staticmethod
    def _payment_totals(reports: list[dict[str, Any]]) -> dict[str, float | int]:
        return {
            "total_cash": sum(r.get("cash_total", 0) for r in reports),
            "total_gcash": sum(r.get("gcash_total", 0) for r in reports),
            "cash_count": sum(r.get("cash_count", 0) for r in reports),
            "gcash_count": sum(r.get("gcash_count", 0) for r in reports),
        }

    def build_pdf_context(
        self,
        reports: list[dict[str, Any]],
        soft_entries: list[dict[str, Any]],
    ) -> dict[str, Any]:
        payments = self._payment_totals(reports)
        return {
            "reports": reports,
            "soft_entries": soft_entries,
            "total_revenue": sum(r["total_revenue"] for r in reports),
            "total_expenses": sum(r["total_expenses"] for r in reports),
            "net_balance": sum(r["net_balance"] for r in reports),
            "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "period_label": self._period_label(reports),
            **payments,
        }

    def export_pdf(
        self,
        reports: list[dict[str, Any]],
        soft_entries: list[dict[str, Any]],
    ) -> Response:
        pdf_bytes = self.render_pdf_bytes(
            self.PDF_TEMPLATE,
            **self.build_pdf_context(reports, soft_entries),
        )
        filename = f"daily_sales_balance_{date.today().isoformat()}.pdf"
        return Response(
            pdf_bytes,
            mimetype="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={filename}"},
        )

    @staticmethod
    def export_csv(reports: list[dict[str, Any]]):
        output = StringIO()
        writer = csv.DictWriter(
            output,
            fieldnames=[
                "Report Date",
                "Total Revenue",
                "Cash",
                "GCash",
                "Total Expenses",
                "Net Balance",
                "Total Orders",
                "Total Sessions",
                "Generated By",
                "Notes",
            ],
        )
        writer.writeheader()
        for report in reports:
            writer.writerow({
                "Report Date": report["report_date"],
                "Total Revenue": f"₱{report['total_revenue']:.2f}",
                "Cash": f"₱{report.get('cash_total', 0):.2f}",
                "GCash": f"₱{report.get('gcash_total', 0):.2f}",
                "Total Expenses": f"₱{report['total_expenses']:.2f}",
                "Net Balance": f"₱{report['net_balance']:.2f}",
                "Total Orders": report["total_orders"],
                "Total Sessions": report["total_sessions"],
                "Generated By": report["generated_by"],
                "Notes": report["notes"] or "",
            })
        output.seek(0)
        bytes_output = BytesIO(output.getvalue().encode("utf-8"))
        return send_file(
            bytes_output,
            mimetype="text/csv",
            as_attachment=True,
            download_name="sales_report.csv",
        )

    def export_excel(self, reports: list[dict[str, Any]]):
        wb = Workbook()
        wb.remove(wb.active)

        ws_summary = wb.create_sheet("Summary")
        self._create_summary_sheet(ws_summary, reports)

        ws_details = wb.create_sheet("Daily Reports")
        self._create_details_sheet(ws_details, reports)

        if len(reports) >= 2:
            ws_comparison = wb.create_sheet("Period Comparison")
            self._create_comparison_sheet(ws_comparison, reports)

        ws_trends = wb.create_sheet("Trends")
        self._create_trends_sheet(ws_trends, reports)

        bytes_output = BytesIO()
        wb.save(bytes_output)
        bytes_output.seek(0)
        return send_file(
            bytes_output,
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            as_attachment=True,
            download_name=f"sales_report_{date.today().isoformat()}.xlsx",
        )

    @staticmethod
    def _create_summary_sheet(ws, reports: list[dict[str, Any]]) -> None:
        ws["A1"] = "SALES SUMMARY REPORT"
        ws["A1"].font = Font(bold=True, size=14)
        ws.merge_cells("A1:H1")

        ws["A3"] = "Key Metrics"
        ws["A3"].font = Font(bold=True, size=11)

        total_revenue = sum(r["total_revenue"] for r in reports)
        total_expenses = sum(r["total_expenses"] for r in reports)
        total_net = sum(r["net_balance"] for r in reports)
        total_cash = sum(r.get("cash_total", 0) for r in reports)
        total_gcash = sum(r.get("gcash_total", 0) for r in reports)

        ws["A4"] = "Total Revenue:"
        ws["B4"] = total_revenue
        ws["B4"].number_format = "₱#,##0.00"

        ws["A5"] = "Cash Payments:"
        ws["B5"] = total_cash
        ws["B5"].number_format = "₱#,##0.00"

        ws["A6"] = "GCash Payments:"
        ws["B6"] = total_gcash
        ws["B6"].number_format = "₱#,##0.00"

        ws["A7"] = "Total Expenses:"
        ws["B7"] = total_expenses
        ws["B7"].number_format = "₱#,##0.00"

        ws["A8"] = "Net Balance:"
        ws["B8"] = total_net
        ws["B8"].number_format = "₱#,##0.00"
        ws["B8"].font = Font(bold=True, color="008000")

        ws["A9"] = "Total Orders:"
        ws["B9"] = sum(r["total_orders"] for r in reports)

        ws["A10"] = "Total Sessions:"
        ws["B10"] = sum(r["total_sessions"] for r in reports)

        ws["A11"] = "Period:"
        if reports:
            ws["B11"] = DailyBalanceExportService._period_label(reports)

    @staticmethod
    def _create_details_sheet(ws, reports: list[dict[str, Any]]) -> None:
        header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
        header_font = Font(bold=True, color="FFFFFF", size=11)
        border = Border(
            left=Side(style="thin"),
            right=Side(style="thin"),
            top=Side(style="thin"),
            bottom=Side(style="thin"),
        )

        headers = [
            "Report Date",
            "Revenue",
            "Cash",
            "GCash",
            "Expenses",
            "Net Balance",
            "Orders",
            "Sessions",
            "Generated By",
            "Notes",
        ]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col)
            cell.value = header
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center")
            cell.border = border

        for row_idx, report in enumerate(reports, 2):
            values = [
                report["report_date"],
                report["total_revenue"],
                report.get("cash_total", 0),
                report.get("gcash_total", 0),
                report["total_expenses"],
                report["net_balance"],
                report["total_orders"],
                report["total_sessions"],
                report["generated_by"],
                report["notes"] or "",
            ]
            for col, value in enumerate(values, 1):
                cell = ws.cell(row=row_idx, column=col)
                cell.value = value
                cell.border = border
                if col in (2, 3, 4, 5, 6):
                    cell.number_format = "₱#,##0.00"

        for col, width in zip("ABCDEFGHIJ", [15, 15, 15, 15, 15, 15, 10, 10, 15, 25]):
            ws.column_dimensions[col].width = width

    @staticmethod
    def _create_comparison_sheet(ws, reports: list[dict[str, Any]]) -> None:
        header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
        header_font = Font(bold=True, color="FFFFFF", size=11)

        ws["A1"] = "Period Comparison"
        ws["A1"].font = Font(bold=True, size=12)

        current = reports[0]
        previous = reports[1] if len(reports) > 1 else None

        for col, label in enumerate(["Metric", "Current Period", "Previous Period", "Change", "% Change"], 1):
            cell = ws.cell(row=3, column=col)
            cell.value = label
            cell.fill = header_fill
            cell.font = header_font

        metrics = [
            ("Revenue", "total_revenue"),
            ("Expenses", "total_expenses"),
            ("Net Balance", "net_balance"),
            ("Orders", "total_orders"),
            ("Sessions", "total_sessions"),
        ]

        for row_idx, (label, key) in enumerate(metrics, 4):
            ws.cell(row=row_idx, column=1).value = label
            ws.cell(row=row_idx, column=2).value = current[key]
            prev_val = previous[key] if previous else 0
            ws.cell(row=row_idx, column=3).value = prev_val
            change = current[key] - prev_val
            ws.cell(row=row_idx, column=4).value = change
            pct_change = (change / prev_val * 100) if prev_val else 0
            ws.cell(row=row_idx, column=5).value = pct_change
            ws.cell(row=row_idx, column=5).number_format = '0.0"%"'
            if isinstance(current[key], float):
                for c in (2, 3, 4):
                    ws.cell(row=row_idx, column=c).number_format = "₱#,##0.00"

    @staticmethod
    def _create_trends_sheet(ws, reports: list[dict[str, Any]]) -> None:
        ws["A1"] = "Trends & Analysis"
        ws["A1"].font = Font(bold=True, size=12)
        ws["A3"] = "Analysis"
        ws["A3"].font = Font(bold=True, size=11)

        if not reports:
            return

        n = len(reports)
        ws["A4"] = "Average Daily Revenue:"
        ws["B4"] = sum(r["total_revenue"] for r in reports) / n
        ws["B4"].number_format = "₱#,##0.00"

        ws["A5"] = "Average Daily Expenses:"
        ws["B5"] = sum(r["total_expenses"] for r in reports) / n
        ws["B5"].number_format = "₱#,##0.00"

        ws["A6"] = "Average Daily Orders:"
        ws["B6"] = sum(r["total_orders"] for r in reports) / n
        ws["B6"].number_format = "0"

        max_revenue_report = max(reports, key=lambda r: r["total_revenue"])
        ws["A7"] = "Highest Revenue Day:"
        ws["B7"] = f"{max_revenue_report['report_date']} (₱{max_revenue_report['total_revenue']:.2f})"

        ws["A8"] = "Total Days Tracked:"
        ws["B8"] = n

        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 30
