from __future__ import annotations

import csv
from datetime import date, datetime, timedelta
from io import StringIO, BytesIO
from typing import Any
from flask import Blueprint, jsonify, request, render_template, session, send_file

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    HAS_OPENPYXL = True
    print("✓ openpyxl imported successfully")
except ImportError as e:
    HAS_OPENPYXL = False
    print(f"✗ Failed to import openpyxl: {e}")

from app.repositories.sales_repository import SalesRepository
from app.services.sales_service import SalesService
from app.utils.auth import admin_required

sales_bp = Blueprint("sales_admin", __name__, url_prefix="/admin/daily-balance")

_service = SalesService(repo=SalesRepository())


@sales_bp.route("", methods=["GET"])
@admin_required
def list_reports() -> str:
    reports = _service.list_reports()
    soft_entries = _service.list_soft_balances()
    return render_template("admin/daily_balance.html", reports=reports, soft_entries=soft_entries)


@sales_bp.route("/api/reports", methods=["GET"])
@admin_required
def api_list_reports() -> tuple:
    reports = _service.list_reports()
    return jsonify({"success": True, "data": reports}), 200


@sales_bp.route("/api/reports", methods=["POST"])
@admin_required
def api_generate_report() -> tuple:
    data = request.get_json()
    report_date = date.fromisoformat(data.get("report_date"))
    result = _service.generate_report(
        report_date=report_date,
        generated_by=session.get("user_id"),
        notes=data.get("notes"),
    )
    return jsonify(result), 201


@sales_bp.route("/api/reports/export-csv", methods=["GET"])
@admin_required
def api_export_csv() -> Any:
    reports = _service.list_reports()
    output = StringIO()
    writer = csv.DictWriter(
        output,
        fieldnames=[
            "Report Date",
            "Total Revenue",
            "Total Expenses",
            "Net Balance",
            "Total Orders",
            "Total Sessions",
            "Generated By",
            "Notes",
        ],
    )
    writer.writeheader()
    for report in reports:
        writer.writerow({
            "Report Date": report["report_date"],
            "Total Revenue": f"₱{report['total_revenue']:.2f}",
            "Total Expenses": f"₱{report['total_expenses']:.2f}",
            "Net Balance": f"₱{report['net_balance']:.2f}",
            "Total Orders": report["total_orders"],
            "Total Sessions": report["total_sessions"],
            "Generated By": report["generated_by"],
            "Notes": report["notes"] or "",
        })

    output.seek(0)
    bytes_output = BytesIO(output.getvalue().encode("utf-8"))
    return send_file(
        bytes_output,
        mimetype="text/csv",
        as_attachment=True,
        download_name="sales_report.csv",
    )


@sales_bp.route("/api/reports/export-excel", methods=["GET"])
@admin_required
def api_export_excel() -> Any:
    try:
        reports = _service.list_reports()
        
        # Create workbook with multiple sheets
        wb = Workbook()
        wb.remove(wb.active)
        
        # Sheet 1: Summary
        ws_summary = wb.create_sheet("Summary")
        _create_summary_sheet(ws_summary, reports)
        
        # Sheet 2: Detailed Daily Reports
        ws_details = wb.create_sheet("Daily Reports")
        _create_details_sheet(ws_details, reports)
        
        # Sheet 3: Period Comparison
        if len(reports) >= 2:
            ws_comparison = wb.create_sheet("Period Comparison")
            _create_comparison_sheet(ws_comparison, reports)
        
        # Sheet 4: Trends & Analysis
        ws_trends = wb.create_sheet("Trends")
        _create_trends_sheet(ws_trends, reports)
        
        # Save to BytesIO
        bytes_output = BytesIO()
        wb.save(bytes_output)
        bytes_output.seek(0)
        
        return send_file(
            bytes_output,
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            as_attachment=True,
            download_name=f"sales_report_{date.today().isoformat()}.xlsx",
        )
    except Exception as e:
        print(f"Error exporting Excel: {e}")
        return jsonify({"error": f"Failed to export Excel: {str(e)}"}), 500


def _create_summary_sheet(ws, reports) -> None:
    """Create summary sheet with key metrics"""
    header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=12)
    
    # Title
    ws['A1'] = "SALES SUMMARY REPORT"
    ws['A1'].font = Font(bold=True, size=14)
    ws.merge_cells('A1:H1')
    
    # Key Metrics
    ws['A3'] = "Key Metrics"
    ws['A3'].font = Font(bold=True, size=11)
    
    total_revenue = sum(r['total_revenue'] for r in reports)
    total_expenses = sum(r['total_expenses'] for r in reports)
    total_net = sum(r['net_balance'] for r in reports)
    total_orders = sum(r['total_orders'] for r in reports)
    total_sessions = sum(r['total_sessions'] for r in reports)
    
    ws['A4'] = "Total Revenue:"
    ws['B4'] = total_revenue
    ws['B4'].number_format = '₱#,##0.00'
    
    ws['A5'] = "Total Expenses:"
    ws['B5'] = total_expenses
    ws['B5'].number_format = '₱#,##0.00'
    
    ws['A6'] = "Net Balance:"
    ws['B6'] = total_net
    ws['B6'].number_format = '₱#,##0.00'
    ws['B6'].font = Font(bold=True, color="008000")
    
    ws['A7'] = "Total Orders:"
    ws['B7'] = total_orders
    
    ws['A8'] = "Total Sessions:"
    ws['B8'] = total_sessions
    
    ws['A9'] = "Period:"
    if reports:
        first_date = reports[-1]['report_date']
        last_date = reports[0]['report_date']
        ws['B9'] = f"{first_date} to {last_date}"


def _create_details_sheet(ws, reports) -> None:
    """Create detailed daily reports sheet"""
    header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Headers
    headers = ["Report Date", "Revenue", "Expenses", "Net Balance", "Orders", "Sessions", "Generated By", "Notes"]
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col)
        cell.value = header
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = border
    
    # Data rows
    for row_idx, report in enumerate(reports, 2):
        ws.cell(row=row_idx, column=1).value = report['report_date']
        ws.cell(row=row_idx, column=2).value = report['total_revenue']
        ws.cell(row=row_idx, column=2).number_format = '₱#,##0.00'
        ws.cell(row=row_idx, column=3).value = report['total_expenses']
        ws.cell(row=row_idx, column=3).number_format = '₱#,##0.00'
        ws.cell(row=row_idx, column=4).value = report['net_balance']
        ws.cell(row=row_idx, column=4).number_format = '₱#,##0.00'
        ws.cell(row=row_idx, column=5).value = report['total_orders']
        ws.cell(row=row_idx, column=6).value = report['total_sessions']
        ws.cell(row=row_idx, column=7).value = report['generated_by']
        ws.cell(row=row_idx, column=8).value = report['notes'] or ""
        
        for col in range(1, 9):
            ws.cell(row=row_idx, column=col).border = border
    
    # Auto-adjust column widths
    ws.column_dimensions['A'].width = 15
    ws.column_dimensions['B'].width = 15
    ws.column_dimensions['C'].width = 15
    ws.column_dimensions['D'].width = 15
    ws.column_dimensions['E'].width = 10
    ws.column_dimensions['F'].width = 10
    ws.column_dimensions['G'].width = 15
    ws.column_dimensions['H'].width = 25


def _create_comparison_sheet(ws, reports) -> None:
    """Create period comparison sheet"""
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    
    ws['A1'] = "Period Comparison"
    ws['A1'].font = Font(bold=True, size=12)
    
    # Get current and previous period
    current = reports[0]
    previous = reports[1] if len(reports) > 1 else None
    
    ws['A3'] = "Metric"
    ws['B3'] = "Current Period"
    ws['C3'] = "Previous Period"
    ws['D3'] = "Change"
    ws['E3'] = "% Change"
    
    for col in range(1, 6):
        ws.cell(row=3, column=col).fill = header_fill
        ws.cell(row=3, column=col).font = header_font
    
    metrics = [
        ("Revenue", "total_revenue"),
        ("Expenses", "total_expenses"),
        ("Net Balance", "net_balance"),
        ("Orders", "total_orders"),
        ("Sessions", "total_sessions"),
    ]
    
    for row_idx, (label, key) in enumerate(metrics, 4):
        ws.cell(row=row_idx, column=1).value = label
        ws.cell(row=row_idx, column=2).value = current[key]
        prev_val = previous[key] if previous else 0
        ws.cell(row=row_idx, column=3).value = prev_val
        change = current[key] - prev_val
        ws.cell(row=row_idx, column=4).value = change
        pct_change = (change / prev_val * 100) if prev_val else 0
        ws.cell(row=row_idx, column=5).value = pct_change
        ws.cell(row=row_idx, column=5).number_format = '0.0"%"'
        
        # Format numbers
        if isinstance(current[key], float):
            ws.cell(row=row_idx, column=2).number_format = '₱#,##0.00'
            ws.cell(row=row_idx, column=3).number_format = '₱#,##0.00'
            ws.cell(row=row_idx, column=4).number_format = '₱#,##0.00'
    
    ws.column_dimensions['A'].width = 15
    ws.column_dimensions['B'].width = 18
    ws.column_dimensions['C'].width = 18
    ws.column_dimensions['D'].width = 15
    ws.column_dimensions['E'].width = 12


def _create_trends_sheet(ws, reports) -> None:
    """Create trends and analysis sheet"""
    header_fill = PatternFill(start_color="70AD47", end_color="70AD47", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    
    ws['A1'] = "Trends & Analysis"
    ws['A1'].font = Font(bold=True, size=12)
    
    # Average metrics
    ws['A3'] = "Analysis"
    ws['A3'].font = Font(bold=True, size=11)
    
    if reports:
        avg_revenue = sum(r['total_revenue'] for r in reports) / len(reports)
        avg_expenses = sum(r['total_expenses'] for r in reports) / len(reports)
        avg_orders = sum(r['total_orders'] for r in reports) / len(reports)
        
        ws['A4'] = "Average Daily Revenue:"
        ws['B4'] = avg_revenue
        ws['B4'].number_format = '₱#,##0.00'
        
        ws['A5'] = "Average Daily Expenses:"
        ws['B5'] = avg_expenses
        ws['B5'].number_format = '₱#,##0.00'
        
        ws['A6'] = "Average Daily Orders:"
        ws['B6'] = avg_orders
        ws['B6'].number_format = '0'
        
        ws['A7'] = "Highest Revenue Day:"
        max_revenue_report = max(reports, key=lambda r: r['total_revenue'])
        ws['B7'] = f"{max_revenue_report['report_date']} (₱{max_revenue_report['total_revenue']:.2f})"
        
        ws['A8'] = "Total Days Tracked:"
        ws['B8'] = len(reports)
    
    ws.column_dimensions['A'].width = 25
    ws.column_dimensions['B'].width = 30


@sales_bp.route("/api/soft-balances", methods=["GET"])
@admin_required
def api_list_soft_balances() -> tuple:
    entries = _service.list_soft_balances()
    return jsonify({"success": True, "data": entries}), 200


@sales_bp.route("/api/soft-balances", methods=["POST"])
@admin_required
def api_create_soft_balance() -> tuple:
    data = request.get_json()
    balance_date = date.fromisoformat(data.get("balance_date"))
    period = (data.get("period") or "AM").upper()
    result = _service.create_soft_balance(
        balance_date=balance_date,
        period=period,
        generated_by=session.get("user_id"),
        notes=data.get("notes"),
    )
    return jsonify(result), 201